version: '3.7'

services: 
  kafka:
    image: confluentinc/cp-kafka:4.1.0
    container_name: kafka
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports: 
      - 9092:9092
    networks: 
      - kafka
  
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    container_name: zookeeper
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
    networks: 
      - kafka

networks:
  kafka: